#!/bin/bash


if [ "$(id -u)" -ne 0 ]; then
  echo "You should login as root user to run this."
  exit 1
fi

if [ -z "$2" ]; then
  echo "Argument new root password missing, --set-root-pass <root-password>"
  exit 1
fi

MYSQL_PASSWORD=$2

if [ -f /etc/.mysql_password_already_set ]; then
  echo "Password already set, You cannot reset the password with mysql_secure_installation"
  exit 0
fi

echo "CREATE USER 'root'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;" >/tmp/.root-pass1.sql
mysql </tmp/.root-pass1.sql &>>/tmp/mysql.log
if [ $? -eq 0 ]; then echo $MYSQL_PASSWORD > /etc/.mysql_password_already_set; fi
