#!/bin/bash

HOST_NAME=$1
if [ -z "$1" ]; then
  echo -e "Give Hostname as Input"
  exit 1
fi

if [ $(id -u) -ne 0 ]; then
  echo "You should be root user to execute this!!"
  exit 1
fi

echo 'export PS1="[ \[\e[1;31m\]\u\[\e[m\]@\[\e[1;33m\]HOST_NAME\[\e[m\] \[\e[1;36m\]\w\[\e[m\] ]\\$ "' >/etc/profile.d/ps1.sh
echo 'export PS1="[ \[\e[1;31m\]\u\[\e[m\]@\[\e[1;33m\]HOST_NAME\[\e[m\] \[\e[1;36m\]\w\[\e[m\] ]\\$ "' >/home/ubuntu/.bashrc
echo 'export PS1="[ \[\e[1;31m\]\u\[\e[m\]@\[\e[1;33m\]HOST_NAME\[\e[m\] \[\e[1;36m\]\w\[\e[m\] ]\\$ "' >/root/.bashrc
echo 'export PS1="[ \[\e[1;31m\]\u\[\e[m\]@\[\e[1;33m\]HOST_NAME\[\e[m\] \[\e[1;36m\]\w\[\e[m\] ]\\$ "' >/etc/skel/.bashrc
sed -i -e "s/HOST_NAME/${HOST_NAME}/" /etc/profile.d/ps1.sh /home/ubuntu/.bashrc /root/.bashrc /etc/skel/.bashrc
chmod +x /etc/profile.d/ps1.sh